Create ML flask app to process translations
software-students-fall2022/final-project-projecto-team11 pull request #4
Opened 2022-12-11 02:49 UTC by hpdouglass

This is a pretty enormous PR, please go over with a fine-toothed comb! The ML client takes in audio via POST requests to `/translation`, and then queues each request up. A configurable number of threads constantly works at the queue, so new requests are never blocked from coming in. Because the audio is saved to Mongo between the time the request comes in and the time it is processed, if the app is closed during processing or while a job is in the queue, these jobs will automatically get loaded into the queue on restart. The queue system also gets around the enormous wait time to load the models. The models are loaded up once when each thread starts, so they are able to work more quickly. If jobs are placed into the queue while the models are still loading, this isn't a problem, because the job will just sit in the queue until a thread starts processing jobs.

Each thread uses a pretty enormous amount of memory. I was only able to use 2 threads comfortably on my machine in testing, so that number is reflected in this PR. We'll have to play around with it when we deploy. Please feel free to scale this up or down depending on how powerful your machine is.

I've tested this on my machine running mongodb, as well as Bruce's client app, and they work just fine together. So as long as the main app doesn't stray from the protocols, it should continue to work.

Todo in future PRs: Add tests, figure out how to restructure app so that I can set the database object based off the flask config, and possibly figure out how to make the number of threads configurable in the command line for easier deployment? Let me know if you can think of anything else.

2022-12-11 22:55 UTC, bxw201 commented on translator-service/translation_sample_data.json
> +{
nit: it would be nice if this was syntactically correct json if we ever wanted to use it for sample input into the db. we can then add the markup into documentation. hardly a big deal though

2022-12-11 22:55 UTC, bxw201 commented on translator-service/translator/__init__.py
> +    NUM_THREADS = 2
Is there any reasonable way to see what this number can be on digital ocean?

2022-12-11 22:58 UTC, bxw201 commented on translator-service/translator/util.py
> +    except pymongo.errors.ConnectionFailure as e:
just a note. with these exceptions caught here, importing db in another file will return None and the error will propagate up anyway. i'm not sure if that's intended or if there's even a need to fix it. just something to point out

2022-12-11 23:00 UTC, bxw201 commented on translator-service/translator/endpoints.py
> +        "user": None,
TODO: sort out user authentication here

2022-12-11 23:04 UTC, bxw201 commented on translator-service/translator/endpoints.py
> +        # Find what HTTP code to return based off translation job status.
i'd honestly be ok if these were the codes we used in prod

2022-12-11 23:22 UTC, hpdouglass commented on translator-service/translation_sample_data.json
> +{
Will do

2022-12-11 23:26 UTC, hpdouglass commented on translator-service/translator/__init__.py
> +    NUM_THREADS = 2
Honestly the best way to do it would be to just run it there and watching the performance of the machine. On my machine, constantly translating (after loading a whole bunch in the queue) with only one thread had all the CPU cores at about 80%, and then when I added a second thread, it would pin all my cores at 100%. So adding a second thread let me use the ~20% of CPU cycles that were going unused before, but adding more threads from there would not really be beneficial. So I think we should start at 2 threads on DigitalOcean, and then hopefully we can monitor the performance of the machine, and adjust accordingly.

2022-12-11 23:27 UTC, bxw201 requested changes
really good pr. most of the things i had are either nitpicks or just stuff to think about. my biggest thing is making functions more testable. lmk what you think

2022-12-11 23:27 UTC, bxw201 commented on translator-service/translator/jobhandler.py
> +job_queue = multiprocessing.Queue()
global variables are hard to write tests for. is there any way we can pass this in as an argument? we can initialize the queue in `__init__.py` then

2022-12-11 23:27 UTC, bxw201 commented on translator-service/translator/mlworker.py
> +    ckpt = 'facebook/m2m100_418M'
initializing a new model and tokenizer dictionary for every job run might take more time. what if we initialized it once and passed it in as an argument?

2022-12-11 23:27 UTC, bxw201 commented on translator-service/translator/mlworker.py
> +    ckpt = 'facebook/m2m100_418M'
on the other hand, iirc it takes less time to initialize after the first job run (though i'm def not 100% sure of this). however passing it in as an argument might also make it easier to test

2022-12-11 23:27 UTC, bxw201 commented on translator-service/translator/mlworker.py
> +    device = None
nit: this can be a one-liner with a ternary operator

2022-12-11 23:27 UTC, bxw201 commented on translator-service/translator/mlworker.py
> +    ckpt = 'facebook/m2m100_418M'
i know that this function is used earlier as an argument so (i think) it requires a specific set of arguments. you can get around this with a lambda function that looks like `lambda tid, job_queue, delay: work(tid, job_queue, delay, translator_model)`

2022-12-11 23:27 UTC, bxw201 commented on translator-service/translator/mlworker.py
> +                # If user tries to exit the program, gracefully exit.
it might be nice to print a message here too

2022-12-11 23:27 UTC, bxw201 commented on translator-service/translator/mlworker.py
> +def work(tid, job_queue, delay):
this is a really large function that might be tough to write tests for. it could be good to break it up into functional components

2022-12-11 23:28 UTC, bxw201 commented on translator-service/translator/__init__.py
> +    NUM_THREADS = 2
sounds good

2022-12-11 23:28 UTC, hpdouglass commented on translator-service/translator/endpoints.py
> +        # Find what HTTP code to return based off translation job status.
Haha, that's just a comment I didn't remove once the codes became a lot simpler. There use to be an if/elif/else block there and this comment was documenting its function.

2022-12-11 23:29 UTC, bxw201 commented on translator-service/translator/mlworker.py
> +    ckpt = 'facebook/m2m100_418M'
my bad. looked through the pr comments. might still be nice for testing reasons but scratch what i said about the performance

2022-12-11 23:33 UTC, hpdouglass commented on translator-service/translator/mlworker.py
> +    ckpt = 'facebook/m2m100_418M'
So, I actually did test this. Originally, there was just one set of models/tokenizers and I passed them in to each thread as an argument. What would happen is that threads would freeze as soon as they were given any translating to do. I'm guessing there's some issue with trying to use the same set of models more than once at a time. So I solved the problem by giving each thread its own set. Perhaps I just implemented the other way incorrectly, but I wasn't able to get it to work with only one set.

2022-12-11 23:37 UTC, hpdouglass commented on translator-service/translator/mlworker.py
> +    ckpt = 'facebook/m2m100_418M'
But to be clear, each thread only loads the models once, when the thread is created.. The model loading code happens before the while loop starts. Once each thread has something to translate, the only calls inside the while loop are to actually invoke the models to start translating.

2022-12-11 23:39 UTC, bxw201 commented on translator-service/translator/mlworker.py
> +    ckpt = 'facebook/m2m100_418M'
makes sense. good stuff

2022-12-11 23:40 UTC, hpdouglass commented on translator-service/translator/mlworker.py
> +                # If user tries to exit the program, gracefully exit.
I originally had messages in both the try and except blocks. In the try block, it was just something like, "Thread {tid}: Found no jobs." Which just spammed the console. And honestly, the only reason I'm listening for the KeyboardInterrput anyway is because if I don't, I get a nasty exception printed whenever you do Ctrl+C. If I added a message like, "Thread {tid}: KeyboardInterrupt found, closing thread," isn't that the point of pressing Ctrl+C in the first place?

2022-12-11 23:54 UTC, hpdouglass commented on translator-service/translator/mlworker.py
> +    device = None
Done

2022-12-12 00:01 UTC, hpdouglass commented on translator-service/translator/endpoints.py
> +        "user": None,
Done. Since we already have provisions to get the ID from the URL I can do this now without having to wait for any work from the auth team.

2022-12-12 04:00 UTC, bxw201 commented on translator-service/translator/mlworker.py
> +                # If user tries to exit the program, gracefully exit.
sure fair enough

2022-12-12 04:01 UTC, bxw201 approved these changes
LGM

2022-12-12 16:03 UTC, merged